### PR TITLE
Adding 'address' property to the Properties class.

### PR DESCRIPTION
**Pull request by shinayser**
I've added the missing `address` property to the `Properties` class. 
It rarely comes up on the mapbox response JSON, but when it does, it is important :)

### CODE REVIEW

**Comment by ketanchoyal** [comment]
Is it tested?

**Comment by shinayser** [comment]
> Is it tested?

Yup :)

**Comment by ketanchoyal** [comment]
You have to push it again with 1.0.6 version and with proper changelog additions

**Comment by shinayser** [comment]
Sure, in what file you want me to note down the changes?

**Comment by ketanchoyal** [comment]
In Changelog.md and don’t forget to change version to 1.0.6

**Comment by shinayser** [comment]
Done!

**Comment by ketanchoyal** [comment]
It has conflicts you have to create a new pull request

**Comment by shinayser** [comment]
Of ourse it has conflits, you asked me to modify the changelog and pubscpec version O.o

**Pull request merged**
