### PR TITLE
Migrating to null safety

### PR DESCRIPTION
**Pull request by shinayser**
Migrating library to null safety

### CODE REVIEW

**Comment by ketanchoyal** [comment]
Awesome @shinayser thank you very much, I have merged this PR in the null-safety branch

**Comment by shinayser** [comment]
No problem bro! When you thinking about publishing it to pub ?

**Comment by ketanchoyal** [comment]
I'm doing it right now, but it's showing an error because of 'color' dependency as it is not hosted on pub

**Comment by ketanchoyal** [comment]
maybe you can publish that package on pub

**Comment by shinayser** [comment]
Yes! That is because color is not migrated yet on pub. So, I migrated it myself and changed the pubspec of mapbox to point to my own color repository.

**Comment by shinayser** [comment]
You don't need to point directly to pub. Just leave the pubspec pointing to my Color repo until the maintainers accept my PR.

**Comment by ketanchoyal** [comment]
Package dependency color is a git dependency, this is not allowed in published packages.
pub finished with exit code 1

This is what I'm getting

**Comment by shinayser** [comment]
Humm I udnerstand. What you think about copying the entire `color` library code to mapbox_search? Since the library is kinda "abandoned" I think can be a good way to avoid this problem in the future.
Also, myself publishing the same package on the pub is a little odd.

**Pull request closed without merging**
